print(bool(0))
print(bool(0b00))
print(bool(0o00))
print(bool(0x00))
print(bool(0.0))
print(bool(0+0j))
print(bool(0-0j))
print(bool(''))
print("----------------------")
print(bool(' '))
print(bool(1))
print(bool(-1))
print(bool(0.0001))
print(bool(1-0j))
print(bool('a'))