string="Python is Easy"
string1="   Python"
string3="Python     "
print("---------------------------")
print("case 1:")
print("Before strip:")
print(string)
print("After strip: ")
print(string.strip())
print("---------------------------")
print("case 2:")
print("Before strip:")
print(string1)
print("After strip: ")
print(string1.strip())
print("---------------------------")
print("case 3:")
print("Before strip:")
print(string3)
print("After strip: ")
print(string3.strip())
print("---------------------------")
