print("---------------------------------------------------------")
print("1.List is ordered.")
print("2.Indexing is possible.")
print("3.Slicing is also possible.")
print("4.List is Homogeneous ==> when the list is defined with same datatype")
print("5.List is Heterogeneous ==> when the list is defined with different datatypes")
print("6.List is mutable datatype")
print("---------------------------------------------------------")
l1=[10,20,30,33,22,11,12,24,36] #homogenous
print("Homogenous List:")
print(l1)
print("---------------------------------------------------------")
l2=[True,'abc',1-23j,1.009,123] #heterogenous
print("Heterogenous List:")
print(l2)
print("---------------------------------------------------------")
print("Display the entire list:")
print(l1)
print("---------------------------------------------------------")
print("Display the list of elements using positive index:")
print(l1[0],l1[1],l1[2])
print("---------------------------------------------------------")
print("Display the list of elements using negative index:")
print(l1[-1],l1[-2],l1[-3])
print("---------------------------------------------------------")
print("1. Start at the beginning of 0.")
print("2. Go until the end (stop is omitted).")
print("3. Take every 3rd element (step is 3).")
print(l1[::3])
print(l1[::-1])
print("---------------------------------------------------------")
print(type(l1))
print(type(l2))
print("---------------------------------------------------------")
print(id(l1))
l1[1] = 110
print(l1)
print(id(l1))
print("---------------------------------------------------------")