print("---------------------------------------------------------")
print("List functions:")
print("3.append()")
print("when we want to add the element at the last in the list, we can use append()")
l=[10,20]
print("Before append:")
print(l)
print("--------------------------------")
l.append(30)
print("After append 30 into list:")
print(l)
print("--------------------------------")
print("After append 40 into list:")
l.append(40)
print(l)
print("--------------------------------")