print("---------------------------------------------------------")
print("List functions:")
print("4.insert()")
print("When we want to add the element at the specified index/position of the list, we can use insert()")
l1 = [10,20]
print("Before insert:")
print(l1)
print("--------------------------------")
l1.insert(1,11)
print("After insert 11 at position 1 into list:")
print(l1)
print("--------------------------------")
l1.insert(2,22)
print("After insert 22 at position 2 into list:")
print(l1)
print("--------------------------------")