print("---------------------------------------------------------")
print("List functions:")
print("5.remove()")
print("When we want to remove the specified element from the list, we can use remove().")
print("--------------------------------")
l1 = [10,20]
print("Before remove:")
print(l1)
print("--------------------------------")
print("After removing 10 from the list:")
l1.remove(10)
print(l1)
print("--------------------------------")
print("After removing 20 from the list:")
l1.remove(20)
print(l1)
print("--------------------------------")